apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-ansible-lab.yaml
  - virtualmachinepool-opensuse-leap.yaml
  - service-opensuse-leap.yaml
  - service-ansible-lab-rke2.yaml
